### ISSUE TITLE
HLA-HD “Couldn't read result file.“

### ISSUE THREAD

**Issue by jingydz** [limbo1996/limbo1996.github.io#1]
您好！
我看到您的"2021-01-23-HLAHD_HLAtyping.md"有提到HLA-HD的使用方法，请问您使用过这个软件吗？有遇到过“Couldn't read result file.”这种报错吗？期待您的回复，感谢您！

**Comment by limbo1996** [comment]
> 您好！
> 我看到您的“ 2021-01-23-HLAHD_HLAtyping.md”有提到HLA-HD的使用方法，请问您使用过这个软件吗？有遇到过“无法读取结果文件。”这种报错吗？期待您的回复，感谢您！

可以把你用到的命令发一下看看么
> hlahd.sh -t 10 -m 0  -c 0.95 -f ~/hla_ii_typing/hlahd.1.3.0/hlahd.1.3.0/freq_data/ \
  $fastqdir/<sample>_1_qc.fq \
  $fastqdir/<sample>_2_qc.fq \
  ~/hla_ii_typing/hlahd.1.3.0/hlahd.1.3.0/HLA_gene.split.txt \
  ~/hla_ii_typing/hlahd.1.3.0/hlahd.1.3.0/dictionary/ \
  <sample> \
  $outdir

这是我用的命令，可能是因为没有指定输出目录的原因。
